"""Tests for `tools/evidence_check.py` (STORY-212) -- the SCRIPT rung of the
evidence-artifact rule.

AC2/AC3/AC4 each require BOTH directions tested (a correct artifact/pair/
mutation passes, a bad one fails) -- this file is that. AC5 (the tool
subjected to its own rule) is demonstrated separately via the real CLI, not
duplicated here; see the story's report for those tails.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import evidence_check
import pytest
from import_provenance import WrongImportRootError

# --- helpers -----------------------------------------------------------------


def _git(args: list[str], cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args], cwd=cwd, capture_output=True, text=True, check=True
    )


def _init_repo(tmp_path: Path) -> Path:
    """A throwaway git repo with one module (`target.py`) and one test file
    (`test_target.py`) whose single test observes `target.py`'s value --
    the fixture `check_mutate`'s tests below apply real patches against."""
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(["init", "-q"], repo)
    _git(["config", "user.email", "test@example.com"], repo)
    _git(["config", "user.name", "Test"], repo)
    (repo / "target.py").write_text("VALUE = 1\n", encoding="utf-8")
    (repo / "test_target.py").write_text(
        "from target import VALUE\n\n\ndef test_value():\n    assert VALUE == 1\n",
        encoding="utf-8",
    )
    _git(["add", "-A"], repo)
    _git(["commit", "-q", "-m", "initial"], repo)
    return repo


def _init_repo_with_failing_test(tmp_path: Path) -> Path:
    """Like `_init_repo`, but `test_value` is already RED at HEAD -- the
    fixture MAJOR 2's baseline check exists to catch (a mutation applied on
    top of an already-failing selector cannot be told apart from a genuine
    RED proof)."""
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(["init", "-q"], repo)
    _git(["config", "user.email", "test@example.com"], repo)
    _git(["config", "user.name", "Test"], repo)
    (repo / "target.py").write_text("VALUE = 1\n", encoding="utf-8")
    (repo / "test_target.py").write_text(
        "from target import VALUE\n\n\ndef test_value():\n    assert VALUE == 999\n",
        encoding="utf-8",
    )
    _git(["add", "target.py", "test_target.py"], repo)
    _git(["commit", "-q", "-m", "initial (already red)"], repo)
    return repo


def _make_patch(repo: Path, tmp_path: Path, new_content: str, name: str) -> Path:
    """Mutate `target.py` to `new_content`, capture the resulting `git diff`
    as a patch file, then reset `target.py` back to its committed state --
    the patch is generated BY git, so it is guaranteed to be a well-formed,
    `git apply`-able unified diff (never a hand-authored one that could
    mismatch context lines)."""
    (repo / "target.py").write_text(new_content, encoding="utf-8")
    diff = _git(["diff"], repo).stdout
    _git(["checkout", "--", "target.py"], repo)
    patch_path = tmp_path / name
    patch_path.write_text(diff, encoding="utf-8")
    return patch_path


def _make_creation_patch(
    repo: Path, tmp_path: Path, filename: str, content: str, name: str
) -> Path:
    """Like `_make_patch`, but for a NEW, currently-untracked file (a
    CREATION patch) -- MAJOR 3's exact blind spot: `git diff -- <path>`
    cannot see an untracked file at all, so a restore check built on it is
    vacuous for exactly this patch shape. Stages just `filename` (never bulk
    `-A`), diffs the staged addition, then unstages and deletes it so the
    repo is back to its committed state before the patch is used."""
    new_file = repo / filename
    new_file.write_text(content, encoding="utf-8")
    _git(["add", filename], repo)
    diff = _git(["diff", "--cached"], repo).stdout
    _git(["reset", "--", filename], repo)
    new_file.unlink()
    patch_path = tmp_path / name
    patch_path.write_text(diff, encoding="utf-8")
    return patch_path


def _write_script(tmp_path: Path, name: str, body: str) -> Path:
    path = tmp_path / name
    path.write_text(body, encoding="utf-8")
    return path


# --- AC2: falsify --------------------------------------------------------


def test_check_falsify_reports_not_a_gate_when_artifact_exits_zero_on_bad_input(
    tmp_path,
):
    script = _write_script(tmp_path, "always_ok.py", "import sys\nsys.exit(0)\n")
    is_gate, message = evidence_check.check_falsify(
        [sys.executable, str(script)], ["--anything"]
    )
    assert is_gate is False
    assert "NOT A GATE" in message


def test_check_falsify_passes_when_artifact_correctly_fails_on_bad_input(tmp_path):
    script = _write_script(tmp_path, "always_fail.py", "import sys\nsys.exit(1)\n")
    is_gate, message = evidence_check.check_falsify(
        [sys.executable, str(script)], ["--anything"]
    )
    assert is_gate is True
    assert "IS a gate" in message


def test_check_falsify_empty_bad_input_is_a_valid_call(tmp_path):
    """Explicit empty-input behaviour (checklist): `bad_input=[]` is a valid
    call, not a crash -- the artifact still runs with no extra argv."""
    script = _write_script(tmp_path, "always_fail2.py", "import sys\nsys.exit(3)\n")
    is_gate, _message = evidence_check.check_falsify([sys.executable, str(script)], [])
    assert is_gate is True


# --- AC3: two-sided (generic command mode) -------------------------------


def test_check_two_sided_fails_when_outcomes_identical(tmp_path):
    script = _write_script(tmp_path, "constant.py", "print('same')\n")
    differ, message = evidence_check.check_two_sided(
        [sys.executable, str(script)], [sys.executable, str(script)]
    )
    assert differ is False
    assert "IDENTICAL" in message


def test_check_two_sided_passes_when_outcomes_genuinely_differ(tmp_path):
    left = _write_script(tmp_path, "left.py", "print('left')\n")
    right = _write_script(tmp_path, "right.py", "print('right')\n")
    differ, message = evidence_check.check_two_sided(
        [sys.executable, str(left)], [sys.executable, str(right)]
    )
    assert differ is True
    assert "DIFFER" in message


def test_check_two_sided_catches_same_exit_code_different_stdout():
    """Guards against comparing exit code ALONE -- two sides that both exit
    0 while printing different numbers must still register as DIFFERENT."""
    differ, _message = evidence_check.check_two_sided(
        [sys.executable, "-c", "print(1)"], [sys.executable, "-c", "print(2)"]
    )
    assert differ is True


def test_check_two_sided_catches_same_exit_code_same_stdout_as_identical():
    """The inverse: identical exit code AND identical stdout is IDENTICAL,
    even though the two invocations are textually different commands --
    this is the shape STORY-220 hit (two proofs firing the same branch)."""
    differ, _message = evidence_check.check_two_sided(
        [sys.executable, "-c", "print(1)"], [sys.executable, "-c", "print(1)"]
    )
    assert differ is False


# --- AC3 + AC6: two-sided --import-provenance-module wrap ------------------


def test_check_two_sided_import_provenance_fails_when_same_root_resolves_both_times(
    tmp_path,
):
    """Reproduces the exact sprint-63 STORY-180 trap `import_provenance.py`
    itself documents: a module that resolves under the SAME root on both
    sides is an IDENTICAL, failed proof."""
    root = tmp_path / "root"
    root.mkdir()
    (root / "_evidence_check_probe_a.py").write_text("MARKER = 1\n", encoding="utf-8")

    sys.path.insert(0, str(root))
    try:
        differ, message = evidence_check.check_two_sided_import_provenance(
            "_evidence_check_probe_a", root, root
        )
        assert differ is False
        assert "IDENTICAL" in message
    finally:
        sys.path.remove(str(root))
        sys.modules.pop("_evidence_check_probe_a", None)


def test_check_two_sided_import_provenance_passes_when_roots_genuinely_differ(
    tmp_path,
):
    root = tmp_path / "root"
    root.mkdir()
    (root / "_evidence_check_probe_b.py").write_text("MARKER = 1\n", encoding="utf-8")
    other_root = tmp_path / "other_root"
    other_root.mkdir()

    sys.path.insert(0, str(root))
    try:
        differ, message = evidence_check.check_two_sided_import_provenance(
            "_evidence_check_probe_b", root, other_root
        )
        assert differ is True
        assert "DIFFER" in message
    finally:
        sys.path.remove(str(root))
        sys.modules.pop("_evidence_check_probe_b", None)


def test_check_two_sided_import_provenance_wraps_assert_import_root_not_reimplemented(
    tmp_path, monkeypatch
):
    """AC6: `check_two_sided_import_provenance` must call through to
    `assert_import_root` -- proven by making the wrapped call itself raise
    a distinctive error and observing it surface as the recorded outcome,
    rather than any independently-reimplemented resolution logic."""

    def fake_assert_import_root(module_name, expected_root):
        # Deliberately ignores expected_root, so both sides raise the
        # IDENTICAL fake error -- proving the wrapper's outcome comes from
        # whatever assert_import_root does, not from an independent
        # left-vs-right resolution this module invented itself.
        raise WrongImportRootError(f"FAKE for {module_name}")

    monkeypatch.setattr(evidence_check, "assert_import_root", fake_assert_import_root)

    differ, message = evidence_check.check_two_sided_import_provenance(
        "whatever", tmp_path / "a", tmp_path / "b"
    )
    assert differ is False
    assert "FAKE for whatever" in message


# --- AC4: mutate ----------------------------------------------------------


def test_check_mutate_turns_test_red_and_restores(tmp_path):
    repo = _init_repo(tmp_path)
    patch_path = _make_patch(repo, tmp_path, "VALUE = 2\n", "breaking.patch")

    turned_red, message = evidence_check.check_mutate(
        patch_path, ["test_target.py"], repo_root=repo
    )

    assert turned_red is True
    assert "test_value" in message

    # Scoped to the mutated target (AC4's own correction) -- not a whole-tree
    # `git status`, which would also flag the __pycache__/ the pytest run
    # itself creates, unrelated to whether the mutation was restored.
    assert _git(["diff", "--", "target.py"], repo).stdout == ""


def test_check_mutate_zero_red_is_a_failure(tmp_path):
    """A mutation that changes nothing the test observes (a comment-only
    edit) turns nothing red -- UNPINNED, and `mutate` must exit non-zero."""
    repo = _init_repo(tmp_path)
    patch_path = _make_patch(repo, tmp_path, "VALUE = 1  # comment\n", "noop.patch")

    turned_red, message = evidence_check.check_mutate(
        patch_path, ["test_target.py"], repo_root=repo
    )

    assert turned_red is False
    assert "ZERO RED" in message
    assert _git(["diff"], repo).stdout == ""


def test_check_mutate_rejects_patch_with_no_target(tmp_path):
    repo = _init_repo(tmp_path)
    empty_patch = tmp_path / "empty.patch"
    empty_patch.write_text("not a real diff\n", encoding="utf-8")

    turned_red, message = evidence_check.check_mutate(
        empty_patch, ["test_target.py"], repo_root=repo
    )
    assert turned_red is False
    assert "names no target file" in message


def test_check_mutate_collection_error_is_not_a_red_proof(tmp_path):
    """CRITICAL (sprint-70 fix round): pytest's collection-error banner line
    (`____________ ERROR collecting test_x.py ____________`) has "ERROR" as
    its SECOND whitespace token, same as a genuine `path/to/test.py::test_fn
    ERROR` result line -- the pre-fix scan could not tell them apart and
    counted the banner's dashes as a "red test id". Probed exactly as
    described: renaming the symbol a test imports (`VALUE` -> `VALUE2`)
    produces an ImportError while collecting, pytest exits 2, and the old
    scan reported `turned_red=True` with a red id made of underscores.
    Fires: the node-id-shape guard on `parts[0]` in `run_pytest_selectors`
    AND the new `_SELECTOR_DID_NOT_RUN_EXIT_CODES` branch in `check_mutate`.
    Would NOT red for an unrelated reason: the baseline (MAJOR 2's fix) is
    green before this patch is applied, since the pre-image `target.py`
    still defines `VALUE` and the pre-image test passes."""
    repo = _init_repo(tmp_path)
    patch_path = _make_patch(repo, tmp_path, "VALUE2 = 1\n", "rename_symbol.patch")

    turned_red, message = evidence_check.check_mutate(
        patch_path, ["test_target.py"], repo_root=repo
    )

    assert turned_red is False
    assert "SELECTOR DID NOT RUN" in message
    assert "UNPINNED" not in message
    assert _git(["diff", "--", "target.py"], repo).stdout == ""


def test_check_mutate_nonexistent_selector_is_not_a_red_proof(tmp_path):
    """CRITICAL, second half: `run_pytest_selectors` discarded pytest's own
    exit code, so a `--tests` naming a nonexistent file returned `red=[]`
    and a baseline-less `check_mutate` would have reported plain "ZERO RED
    -- UNPINNED", a diagnosis it cannot justify (it never even ran the real
    selector). With MAJOR 2's baseline check now in place, this exact case
    surfaces one step earlier, at the baseline: pytest's exit 4 (usage
    error: file not found) is inspected there first, and the tool refuses to
    treat a nonexistent selector as a demonstrated mutation proof either
    way. Fires: the `baseline_exit != 0` branch. Would NOT red for an
    unrelated reason: `real_mutation.patch` is itself a genuine, applicable,
    behaviour-changing patch -- only the selector name is wrong, isolating
    the exit-code defect from the patch-application path."""
    repo = _init_repo(tmp_path)
    patch_path = _make_patch(repo, tmp_path, "VALUE = 2\n", "real_mutation.patch")

    turned_red, message = evidence_check.check_mutate(
        patch_path, ["no_such_selector.py"], repo_root=repo
    )

    assert turned_red is False
    assert "UNPINNED" not in message
    assert "BASELINE NOT GREEN" in message


def test_check_mutate_baseline_not_green_is_not_a_red_proof(tmp_path):
    """MAJOR 2 (sprint-70 fix round): without a baseline run, an
    already-failing selector cannot be distinguished from "the mutation
    turned it red" -- so a purely comment-only, behaviour-preserving patch
    on top of an already-red selector would (pre-fix) still report
    `turned_red=True`. Fires: the new baseline check at the top of
    `check_mutate`, before `git apply` is ever invoked. Would NOT red for an
    unrelated reason: the patch never gets applied at all (asserted via the
    empty `git diff` below), so there is no path-application defect to
    conflate this with."""
    repo = _init_repo_with_failing_test(tmp_path)
    patch_path = _make_patch(
        repo,
        tmp_path,
        "VALUE = 1  # comment, no behaviour change\n",
        "noop_on_red.patch",
    )

    turned_red, message = evidence_check.check_mutate(
        patch_path, ["test_target.py"], repo_root=repo
    )

    assert turned_red is False
    assert "BASELINE NOT GREEN" in message
    assert _git(["diff"], repo).stdout == ""


def test_check_mutate_reports_git_apply_failure(tmp_path):
    """A patch that cannot apply at all (context mismatch) fails loudly at
    the apply step -- never silently treated as zero RED."""
    repo = _init_repo(tmp_path)
    bad_patch = tmp_path / "bad.patch"
    bad_patch.write_text(
        "--- a/target.py\n+++ b/target.py\n@@ -1,1 +1,1 @@\n-VALUE = 999\n+VALUE = 2\n",
        encoding="utf-8",
    )

    turned_red, message = evidence_check.check_mutate(
        bad_patch, ["test_target.py"], repo_root=repo
    )
    assert turned_red is False
    assert "git apply" in message
    assert _git(["diff"], repo).stdout == ""


def test_check_mutate_reports_restore_failed_when_reverse_apply_errors(
    tmp_path, monkeypatch
):
    """Simulates `git apply -R` itself exiting non-zero -- the first of the
    two independent restore-failure branches (AC4: "a failure to restore is
    itself a non-zero exit, never a silent pass")."""
    repo = _init_repo(tmp_path)
    patch_path = _make_patch(repo, tmp_path, "VALUE = 2\n", "breaking2.patch")
    real_apply_patch = evidence_check.apply_patch

    def fake_apply_patch(patch_path_arg, *, cwd, reverse=False):
        if reverse:
            return subprocess.CompletedProcess(
                args=["git", "apply", "-R"],
                returncode=1,
                stdout="",
                stderr="simulated revert failure",
            )
        return real_apply_patch(patch_path_arg, cwd=cwd, reverse=reverse)

    monkeypatch.setattr(evidence_check, "apply_patch", fake_apply_patch)

    turned_red, message = evidence_check.check_mutate(
        patch_path, ["test_target.py"], repo_root=repo
    )
    assert turned_red is False
    assert "RESTORE FAILED" in message

    # The simulated failure means the real revert never ran -- clean up by hand.
    _git(["checkout", "--", "target.py"], repo)
    assert _git(["diff"], repo).stdout == ""


def test_check_mutate_restore_incomplete_detected_for_creation_patch(
    tmp_path, monkeypatch
):
    """MAJOR 3 (sprint-70 fix round): `git diff -- <target>` cannot see an
    UNTRACKED file, and a CREATION patch's target is untracked by
    construction -- probed by simulating a reverse-apply that REPORTS
    success (exit 0) while leaving the newly-created file on disk. The old
    `git diff`-based check would read this as a clean restore (exit 0,
    claiming success); `git status --porcelain` sees the untracked leftover
    and correctly reports RESTORE INCOMPLETE. Fires: the
    `status_result.stdout.strip()` branch. Would NOT red for an unrelated
    reason: the baseline run only touches `test_target.py`/`target.py`,
    which the creation patch never mutates, so the baseline is green and the
    fake reverse-apply is the sole cause of the non-clean restore."""
    repo = _init_repo(tmp_path)
    patch_path = _make_creation_patch(
        repo, tmp_path, "new_module.py", "NEW = 1\n", "creation.patch"
    )
    real_apply_patch = evidence_check.apply_patch

    def fake_apply_patch(patch_path_arg, *, cwd, reverse=False):
        if reverse:
            # Reports success but does NOT actually remove the created file.
            return subprocess.CompletedProcess(
                args=["git", "apply", "-R"], returncode=0, stdout="", stderr=""
            )
        return real_apply_patch(patch_path_arg, cwd=cwd, reverse=reverse)

    monkeypatch.setattr(evidence_check, "apply_patch", fake_apply_patch)

    turned_red, message = evidence_check.check_mutate(
        patch_path, ["test_target.py"], repo_root=repo
    )
    assert turned_red is False
    assert "RESTORE INCOMPLETE" in message

    # The simulated failure means the real revert never ran -- clean up by hand.
    (repo / "new_module.py").unlink()
    assert _git(["status", "--porcelain"], repo).stdout == ""


def test_check_mutate_reports_restore_incomplete_when_diff_still_dirty(
    tmp_path, monkeypatch
):
    """Simulates `git apply -R` REPORTING success (exit 0) while the tree
    stays dirty -- the second, independent restore-failure branch, distinct
    from the exit-code check above."""
    repo = _init_repo(tmp_path)
    patch_path = _make_patch(repo, tmp_path, "VALUE = 2\n", "breaking3.patch")
    real_apply_patch = evidence_check.apply_patch

    def fake_apply_patch(patch_path_arg, *, cwd, reverse=False):
        if reverse:
            # Reports success but does NOT actually revert the file.
            return subprocess.CompletedProcess(
                args=["git", "apply", "-R"], returncode=0, stdout="", stderr=""
            )
        return real_apply_patch(patch_path_arg, cwd=cwd, reverse=reverse)

    monkeypatch.setattr(evidence_check, "apply_patch", fake_apply_patch)

    turned_red, message = evidence_check.check_mutate(
        patch_path, ["test_target.py"], repo_root=repo
    )
    assert turned_red is False
    assert "RESTORE INCOMPLETE" in message

    _git(["checkout", "--", "target.py"], repo)
    assert _git(["diff"], repo).stdout == ""


# --- parse_patch_targets ---------------------------------------------------


def test_parse_patch_targets_reads_plus_plus_plus_header(tmp_path):
    patch_path = tmp_path / "sample.patch"
    patch_path.write_text(
        "--- a/some/file.py\n+++ b/some/file.py\n@@ -1,1 +1,1 @@\n-x = 1\n+x = 2\n",
        encoding="utf-8",
    )
    assert evidence_check.parse_patch_targets(patch_path) == ["some/file.py"]


def test_parse_patch_targets_empty_file_returns_empty_list(tmp_path):
    """Explicit empty-input behaviour: a patch with no recognisable header
    yields the empty list, never a crash."""
    patch_path = tmp_path / "empty.patch"
    patch_path.write_text("", encoding="utf-8")
    assert evidence_check.parse_patch_targets(patch_path) == []


def test_parse_patch_targets_skips_dev_null_deletions(tmp_path):
    patch_path = tmp_path / "deletion.patch"
    patch_path.write_text(
        "--- a/some/file.py\n+++ /dev/null\n@@ -1,1 +0,0 @@\n-x = 1\n",
        encoding="utf-8",
    )
    assert evidence_check.parse_patch_targets(patch_path) == []


# --- CLI wiring -------------------------------------------------------------


def test_main_falsify_returns_1_when_artifact_is_not_a_gate(tmp_path, capsys):
    script = _write_script(tmp_path, "always_ok2.py", "import sys\nsys.exit(0)\n")
    exit_code = evidence_check.main(
        ["falsify", f"{sys.executable} {script}", "--bad-input=--x"]
    )
    assert exit_code == 1
    assert "NOT A GATE" in capsys.readouterr().out


def test_main_two_sided_returns_0_when_sides_differ(capsys):
    exit_code = evidence_check.main(
        [
            "two-sided",
            "--left",
            f"{sys.executable} -c print(1)",
            "--right",
            f"{sys.executable} -c print(2)",
        ]
    )
    assert exit_code == 0
    assert "DIFFER" in capsys.readouterr().out


def test_main_requires_a_subcommand():
    with pytest.raises(SystemExit):
        evidence_check.main([])
