app:
  id: httpcheck
  name: HTTP Check
  monitor_provider: dynatrace
components:
  - id: http-check
    name: HTTP Check
    statuspage_component_id: xdnywbx77npw
    monitors:
      - { signal_key: http-check, native_id: HTTP_CHECK-38B092E93932C002, name: HTTP Check, interval_seconds: 120 }
thresholds: { major: 5, partial: 3, degraded: 2, recovery: 2 }
